name: Fetch Data & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *' # nightly UTC

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::165152433203:role/test-terraform-gha-5
          aws-region: us-east-1

      - name: Get Preset credentials from AWS SSM
        id: get-credentials
        run: |
          PRESET_CREDS=$(aws ssm get-parameter --name "/dataops/preset/data-ops-team-api-token" --with-decryption --query "Parameter.Value" --output text)
          echo "PRESET_API_TOKEN=$(echo $PRESET_CREDS | jq -r '.api_token')" >> $GITHUB_ENV
          echo "PRESET_API_SECRET=$(echo $PRESET_CREDS | jq -r '.api_secret')" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Fetch Preset data
        run: npm run fetch:data

      - name: Build
        run: npm run build
      - name: Prepare Pages artifacts
        run: |
          touch dist/.nojekyll
          echo "Deployment commit: $(date -u)" > dist/DEPLOY_INFO.txt
      - name: Push to gh-pages
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: dist
